image: docker:1.12
services:
    - docker:dind
build_image:
  script:
    - docker -v

    - docker build -t ~/Documents/Workspace/docker/toolbox:php-5.6 php/5.6
    - docker push ~/Documents/Workspace/docker/toolbox:php-5.6

    - docker build -t ~/Documents/Workspace/docker/toolbox:php-7.0 php/7.0
    - docker push ~/Documents/Workspace/docker/toolbox:php-7.0

    - docker build -t ~/Documents/Workspace/docker/toolbox:php-7.1 php/7.1
    - docker push ~/Documents/Workspace/docker/toolbox:php-7.1

    - docker build -t ~/Documents/Workspace/docker/toolbox:php-latest php/latest
    - docker push ~/Documents/Workspace/docker/toolbox:php-latest
